apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-ka5b
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-830-0098-tenant/ci1t-830-0098-app/devfile-sample-ka5b@sha256:f0895b834ee38b7efced25fece69977567c6ba4c707df70db0003d35ff77811e
        name: my-nodejs
        resources: {}
status: {}
